name: themovie
description: A new Flutter application The Movie

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  built_value: ^7.1.0
  chopper: ^3.0.5

  moor_flutter: ^3.1.0
  sqlite3_flutter_libs: ^0.4.0+1
  path_provider: ^1.6.27
  path: ^1.7.0

  cached_network_image: ^2.5.0
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.12.0
  built_value_generator: ^7.1.0
  chopper_generator: ^3.0.5
  moor_generator: ^3.3.1
  json_serializable: ^3.5.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/



